# "/Government/Boards",
# "/Government/Commissions",
# "/How-Do-I/Neighborhood-Police-Officer-NPO-program/7TH-PRECINCT-NPO",
# "/How-Do-I/Neighborhood-Police-Officer-NPO-program/8TH-PRECINCT-NPO",
# "/How-Do-I/Neighborhood-Police-Officer-NPO-program/9TH-PRECINCT-NPO",
# "/How-Do-I/Neighborhood-Police-Officer-NPO-program/GAMING-NPO",
# "/How-Do-I/Do-Business-with-the-City/Planning-Development-RFQs",
# "/Calendar-and-Events",
# "/Calendar-Events",
# "/Government/City-Council/George-Cushingberry",

# "/Detroit-Dashboard",


urls = [
    "/2016-Crime-Statistics",
    "/Boards/BoardOfPoliceCommissioners",
    "/BSEED",
    "/businessincometax",
    "/CampauBanglatown",
    "/Correspondence",
    "/DACC",
    "/DDOT",
    "/Demolition",
    "/Detroit-Demolition-Program/View-All-Demolitions",
    "/Detroit-Opportunities",
    "/Detroit-Opportunities/Find-A-Job",
    "/Detroit-Opportunities/Help-with-your-Home",
    "/Detroit-Opportunities/Programs-for-Youth",
    "/Detroit-Opportunities/Start-or-Grow-Your-Business",
    "/Detroit-Opportunities/Start-or-Grow-Your-Business/Contractor-for-Rehabbed-and-Ready-Program",
    "/doglicense",
    "/Drainage",
    "/dwsd",
    "/DWSDCustomerCare",
    "/DWSDkiosk",
    "/DWSDSkipTheLine",
    "/elections",
    "/employment",
    "/fintreasury",
    "/Government/Boards/Board-of-Electrical-Examiners-Forms",
    "/Government/City-Clerk",
    "/Government/City-Council",
    "/Government/City-Council/Andre-Spivey",
    "/Government/city-council/city-council-district-4/task-forces",
    "/Government/City-Council/Brenda-Jones",
    "/Government/city-council/city-council-president/skilled-trades-task-force",
    "/Government/City-Council/City-Council-Sessions",
    "/Government/City-Council/Gabe-Leland",
    "/Government/City-Council/James-Tate",
    "/Government/city-council/city-council-district-1/task-force",
    "/Government/City-Council/Janee-L-Ayers",
    "/Government/city-council/city-council-large/returning-citizens-task-force",
    "/Government/city-council/city-council-large/letter-residents-detroit",
    "/Government/City-Council/Mary-Sheffield",
    "/government/city-council/city-council-district-5/district-5-neighborhood-police",
    "/government/city-council/city-council-district-5/statements",
    "/Government/City-Council/Raquel-Castaneda-Lopez",
    "/Government/city-council/city-council-district-6/immigation-task-force",
    "/Government/City-Council/Scott-Benson",
    "/Government/Departments",
    "/Government/Departments-and-Agencies/Detroit-Department-of-Transportation/DDOT-News-and-Alerts",
    "/Government/Departments-and-Agencies/Detroit-Health-Department/Detroit-ID",
    "/Government/Departments-and-Agencies/Detroit-Health-Department/Food-Safety",
    "/Government/Departments-and-Agencies/Detroit-Health-Department/Immunizations",
    "/Government/Departments-and-Agencies/Detroit-Health-Department/Sexually-Transmitted-Diseases",
    "/Government/Departments-and-Agencies/Law-Department",
    "/Government/Departments-and-Agencies/Office-of-the-Chief-Financial-Office/Office-of-the-Assessor",
    "/Government/Departments-and-Agencies/Planning-and-Development-Department",
    "/Government/Departments-and-Agencies/Planning-and-Development-Department/Staff-Info",
    "/Government/Departments-and-Agencies/Public-Works/Contact-us",
    "/Government/Departments-and-Agencies/Public-Works/Curbside-Bulk-Waste-Pickup",
    "/Government/Departments-and-Agencies/Public-Works/Recycle",
    "/Government/Departments-and-Agencies/Water-and-Sewerage-Department/About-DWSD",
    "/Government/Departments-and-Agencies/Water-and-Sewerage-Department/Learn-About-Your-Water-and-Sewer-Bill",
    "/Government/Detroit-Police-Commissioners-Meetings",
    "/Government/Mayors-Office",
    "/Government/Mayors-Office/Administration",
    "/health",
    "/How-Do-I",
    "/How-Do-I/Appeal",
    "/How-Do-I/Appeal/Property-Assessment-Forms",
    "/How-Do-I/Apply-for-Licenses",
    "/How-Do-I/Apply-for-Licenses/Boiler-License-Information",
    "/How-Do-I/Apply-for-Licenses/Buildings-License-Information",
    "/How-Do-I/Apply-for-Licenses/Business-License-Checklist",
    "/How-Do-I/Apply-for-Licenses/Business-License-Forms",
    "/How-Do-I/Apply-for-Permits",
    "/How-Do-I/Apply-for-Permits/Building-Inspection-Information",
    "/How-Do-I/Apply-for-Permits/Building-Permit-FAQ",
    "/How-Do-I/Apply-for-Permits/Building-Permit-Information",
    "/How-Do-I/Apply-for-Permits/Gun-Permits-Information",
    "/How-Do-I/Apply-for-Permits/Special-Events-Information",
    "/How-Do-I/Apply-for-Permits/Zoning-Map-Index",
    "/How-Do-I/Apply-for-Permits/Zoning-Permit-Forms",
    "/How-Do-I/Apply-for-Permits/Zoning-Permit-Information",
    "/How-Do-I/Construction-Division-Information",
    "/How-Do-I/Do-Business-with-the-City",
    "/How-Do-I/Do-Business-with-the-City/Building-Authority-Advertisements",
    "/How-Do-I/Do-Business-with-the-City/Open-Bids-for-the-City-of-Detroit",
    "/How-Do-I/File",
    "/How-Do-I/File/Blight-Complaint",
    "/How-Do-I/File/Income-Tax-Forms",
    "/How-Do-I/File/Income-Tax-Information",
    "/How-Do-I/Find",
    "/How-Do-I/Find-Community-Services",
    "/How-Do-I/Find-Community-Services/Arson-Awareness",
    "/How-Do-I/Find-Community-Services/Keep-the-Water-On",
    "/How-Do-I/Find-Detroit-Archives",
    "/How-Do-I/Find-Detroit-Archives/City-Clerks-Archives-and-Records-Information",
    "/How-Do-I/Find-Transportation/Buy-A-Pass",
    "/How-Do-I/Find/Adams-Butzel-Complex",
    "/How-Do-I/Find/Birth-and-Death-Certificates",
    "/How-Do-I/Find/City-Employee-Information",
    "/How-Do-I/Find/Detroit-Animal-Care-and-Control",
    "/How-Do-I/Find/Detroit-Parks-Recreation/Hart-Plaza",
    "/How-Do-I/Find/Detroit-Parks-Recreation/Parks-Recreation-Forms",
    "/How-Do-I/Find/DPD-Jobs",
    "/How-Do-I/Find/DWSD-Alerts-and-News",
    "/How-Do-I/Find/DWSD-Associations",
    "/How-Do-I/Find/Employee-Forms",
    "/How-Do-I/Find/Hotline-Numbers",
    "/How-Do-I/Find/Medical-Marihuana-FAQs",
    "/How-Do-I/FInd/Municipal-Parking-FAQ",
    "/How-Do-I/Find/Payment-Plan",
    "/How-Do-I/Find/Police-Precincts",
    "/How-Do-I/Find/properties/Properties-FAQs",
    "/How-Do-I/Find/Recycling-Information",
    "/How-Do-I/Find/Refuse-Collection",
    "/How-Do-I/Find/Schedule-An-Appointment",
    "/How-Do-I/Find/Water-Sewer-and-Drainage-Rates-101",
    "/How-Do-I/Grants",
    "/How-Do-I/Locate-Transportation",
    "/How-Do-I/Locate-Transportation/Bus-Schedules",
    "/How-Do-I/Locate-Transportation/Bus-Schedules-Information",
    "/How-Do-I/Locate-Transportation/Metro-Lift-Requirements",
    "/How-Do-I/Locate-Transportation/Transportation-Fares",
    "/How-Do-I/Medical-Marihuana-Information",
    "/ImproveDetroit",
    "/How-Do-I/MobileApps",
    "/How-Do-I/My-District",
    "/How-Do-I/Neighborhood-Police-Officer-NPO-program",
    "/How-Do-I/Obtain-Grant-Information/Home-Repair-Program-Information",
    "/How-Do-I/Obtain-Grant-Information/Renaissance-Zones",
    "/How-Do-I/Pay",
    "/How-Do-I/Pay/Blight-Ticket-FAQ",
    "/How-Do-I/Pay/Delinquent-Property-Tax-Information",
    "/How-Do-I/Pay/Pay-Parking-Ticket",
    "/How-Do-I/Pay/Police-Records-and-Reports-Information",
    "/How-Do-I/Pay/Property-Taxes-FAQs",
    "/How-Do-I/Pay/Property-Taxes-Information",
    "/How-Do-I/Pay/Water-Bill-Locations",
    "/How-Do-I/Property-Assessment-Documents",
    "/How-Do-I/Register",
    "/How-Do-I/Register/Register-A-Rental-Property",
    "/How-Do-I/Report",
    "/How-Do-I/Report/Abandoned-Vehicle",
    "/How-Do-I/Report/Crime",
    "/How-Do-I/Report/Dead-Animal-Removal",
    "/How-Do-I/Request-a-Service",
    "/How-Do-I/Request-a-Service/Council-Awards-and-Resolutions",
    "/How-Do-I/Request-a-Service/DPW-Container-Services",
    "/How-Do-I/Request-a-Service/Street-Maintenance",
    "/How-Do-I/Request-a-Service/Tree-Services",
    "/How-Do-I/View-City-of-Detroit-Reports",
    "/How-Do-I/View-City-of-Detroit-Reports/Legislative-Policy-Division-Reports",
    "/How-Do-I/View-Publications-and-Newsletters/Construction-Codes",
    "/How-Do-I/Volunteer/MotorCity-Makeover-Information",
    "/IncomeTax",
    "/Mayors-Help-Desk",
    "/MediaServices",
    "/MedicalMarihuana",
    "/Neighborhoods",
    "/News",
    "/parking",
    "/Police",
    "/projectcleanslate",
    "/properties",
    "/PublicWorks",
    "/Purchasing",
    "/recreation",
    "/rental",
    "/rental/property-registration",
    "/rental/Schedule-Property-Inspection",
    "/Serve-Detroit",
    "/Supplier",
    "/youthprograms",
    "/government/city-clerk",
    "/government/city-clerk/appear-council",
    "/government/city-clerk/banner-permits-information",
    "/government/city-clerk/city-clerk-archive-records-fees",
    "/government/city-clerk/city-clerks-archives-and-records-information",
    "/government/city-clerk/city-council-proceedings-2000-2014-information",
    "/government/city-clerk/city-of-detroit-charter-information",
    "/government/city-clerk/lobbyist-registration-and-reporting-information",
    "/government/city-clerk/elections/become-election-day-pollworker",
    "/government/city-clerk/elections/election-information",
    "/government/city-clerk/elections/election-results",
    "/government/city-clerk/elections/m-100-automark-voting-system",
    "/government/city-clerk/elections/request-absentee-ballot",
]

# city council urls
city_council_urls = [
    "/Government/City-Council",
    "/government/city-council/city-council-president",
    "/Government/city-council/city-council-president/skilled-trades-task-force",
    "/government/city-council/city-council-large",
    "/government/city-council/city-council-large/returning-citizens-task-force",
    "/Government/city-council/city-council-large/letter-residents-detroit",
    "/government/city-council/city-council-district-1",
    "/government/city-council/city-council-district-1/task-force",
    "/government/city-council/city-council-district-2",
    "/government/city-council/city-council-district-2/mental-health-task-force",
    "/government/city-council/city-council-district-3",
    "/government/city-council/city-council-district-3/green-task-force",
    "/government/city-council/city-council-district-4",
    "/government/city-council/city-council-district-4/task-forces",
    "/government/city-council/city-council-district-5",
    "/government/city-council/city-council-district-5/district-5-neighborhood-police",
    "/government/city-council/city-council-district-5/statements",
    "/government/city-council/city-council-district-6",
    "/government/city-council/city-council-district-6/immigation-task-force",
    "/government/city-council/city-council-district-7",
    "/government/city-council/city-council-standing-committees-information",
    "/government/city-council/council-awards-and-resolutions",
    "/government/city-council/legislative-policy-division",
    "/government/city-council/legislative-policy-division/fiscal-analysis-reports",
]

ddot_urls = [
    "/departments/detroit-department-transportation",
    "/departments/detroit-department-transportation/bus-schedules",
    "/departments/detroit-department-transportation/buy-pass",
    "/departments/detroit-department-transportation/metrolift-ada-paratransit-services",
    "/departments/detroit-department-transportation/transportation-fares",
]

dfd_urls = [
    "/departments/detroit-fire-department/arson-awareness",
]

dpd_urls = [
    "/departments/police-department",
    "/departments/police-department/2016-crime-statistics",
    "/departments/police-department/abandoned-vehicle",
    "/departments/police-department/detroit-police-department-jobs",
    "/departments/police-department/detroit-police-department-records-and-reports",
    "/departments/police-department/gun-permits-information",
    "/departments/police-department/precincts-and-neighborhood-police-officers",
    "/departments/police-department/report-crime",
]

bseed_urls = [
    "/departments/buildings-safety-engineering-and-environmental-department",
    "/departments/buildings-safety-engineering-and-environmental-department/building-permit-information",
    "/departments/buildings-safety-engineering-and-environmental-department/business-license-center",
    "/departments/buildings-safety-engineering-and-environmental-department/business-licenses-checklist",
    "/departments/buildings-safety-engineering-and-environmental-department/construction",
    "/departments/buildings-safety-engineering-and-environmental-department/construction/boiler",
    "/departments/buildings-safety-engineering-and-environmental-department/construction/building",
    "/departments/buildings-safety-engineering-and-environmental-department/construction/building-codes",
    "/departments/buildings-safety-engineering-and-environmental-department/medical-marijuana",
    "/departments/buildings-safety-engineering-and-environmental-department/property-maintenance-division",
    "/departments/buildings-safety-engineering-and-environmental-department/property-maintenance-division/certificate-compliance",
    "/departments/buildings-safety-engineering-and-environmental-department/property-maintenance-division/certificate-compliance/quick-steps-obtain-certificate",
    "/departments/buildings-safety-engineering-and-environmental-department/zoning",
]

pdd_urls = [
    "/departments/planning-and-development-department",
    "/departments/planning-and-development-department/citywide-initiatives/home-repair-program-information",
    "/departments/planning-and-development-department/east-design-region/campau-banglatown",
]

dah_urls = [
    "/departments/department-appeals-and-hearings/blight-ticket-information",
]

city_clerk_urls = [
    "/government/city-clerk",
    "/government/city-clerk/appear-council",
    "/government/city-clerk/banner-permits-information",
    "/government/city-clerk/city-clerk-archive-records-fees",
    "/government/city-clerk/city-council-proceedings-2000-2014-information",
    "/government/city-clerk/city-detroit-charter-information",
    "/government/city-clerk/elections",
    "/government/city-clerk/elections/become-election-day-pollworker",
    "/government/city-clerk/elections/election-information",
    "/government/city-clerk/elections/election-results",
    "/government/city-clerk/elections/m-100-automark-voting-system",
    "/government/city-clerk/elections/request-absentee-ballot",
    "/government/city-clerk/lobbyist-registration-and-reporting-information",
]

mayors_office_urls = [
    "/government/mayors-office",
    "/government/mayors-office/mayor",
    "/government/mayors-office/police-chief",
    "/government/mayors-office/chief-staff",
    "/government/mayors-office/corporation-counsel",
    "/government/mayors-office/chief-financial-officer",
    "/government/mayors-office/chief-information-officer",
    "/government/mayors-office/correspondence",
    "/government/mayors-office/group-executive-operations",
    "/government/mayors-office/detroit-neighborhood-initiative",
    "/government/mayors-office/detroit-opportunities",
    "/government/mayors-office/detroit-opportunities/detroit-experiences",
    "/government/mayors-office/detroit-opportunities/find-job",
    "/government/mayors-office/water-and-sewerage-director",
    "/government/mayors-office/group-executive-jobs-and-economic-growth",
    "/government/mayors-office/group-executive-neighborhoods",
    "/government/mayors-office/transportation-director",
    "/government/mayors-office/goal-detroit",
    "/government/mayors-office/human-resources-director",
    "/government/mayors-office/chief-learning-officer",
    "/government/mayors-office/director-and-health-officer",
    "/government/mayors-office/lean-training",
    "/government/mayors-office/mayors-help-desk",
    "/government/mayors-office/office-immigrant-affairs",
    "/government/mayors-office/office-immigrant-affairs/community-resources",
    "/government/mayors-office/office-immigrant-affairs/economic-empowerment",
    "/government/mayors-office/office-immigrant-affairs/education-esl-services",
    "/government/mayors-office/office-immigrant-affairs/employment-resources",
    "/government/mayors-office/office-immigrant-affairs/health-care",
    "/government/mayors-office/office-immigrant-affairs/housing",
    "/government/mayors-office/office-immigrant-affairs/legal-help",
    "/government/mayors-office/office-immigrant-affairs/mayors-welcoming-letter",
    "/government/mayors-office/office-immigrant-affairs/social-services",
    "/government/mayors-office/office-immigrant-affairs/start-business",
    "/government/mayors-office/office-immigrant-affairs/transportation",
    "/government/mayors-office/office-immigrant-affairs/think-detroit",
    "/government/mayors-office/office-sustainability",
    "/government/mayors-office/office-sustainability/current-focus-areas",
    "/government/mayors-office/office-sustainability/mission-and-vision",
    "/government/mayors-office/office-sustainability/sustainability-action-agenda",
    "/government/mayors-office/properties",
    "/government/mayors-office/real-estate-development",
    "/government/mayors-office/real-estate-development/development-financing",
    "/government/mayors-office/real-estate-development/development-how",
    "/government/mayors-office/real-estate-development/development-success-stories",
    "/government/mayors-office/real-estate-development/why-detroit",
    "/government/mayors-office/tax-preparation-checklist",
]

dwsd_urls = [
    "/departments/water-and-sewerage-department",
    "/departments/water-and-sewerage-department/customer-care",
    "/departments/water-and-sewerage-department/customer-care/how-am-i-charged",
    "/departments/water-and-sewerage-department/customer-care/learn-about-your-water-and-sewer-bill",
    "/departments/water-and-sewerage-department/customer-care/where-do-i-pay",
    "/departments/water-and-sewerage-department/drainage-charge",
    "/departments/water-and-sewerage-department/resources/about-dwsd",
    "/departments/water-and-sewerage-department/resources/dwsd-associations",
    "/departments/water-and-sewerage-department/resources/payment-kiosks",
    "/departments/water-and-sewerage-department/resources/payment-plan",
]

media_services_urls = [
    "/departments/media-services-department",
    "/departments/media-services-department/special-events",
]

ocfo_urls = [
    "/departments/office-chief-financial-officer/ocfo-divisions/office-assessor",
    "/departments/office-chief-financial-officer/ocfo-divisions/office-assessor/property-tax-assistance",
    "/departments/office-chief-financial-officer/ocfo-divisions/office-assessor/renaissance-zones",
    "/departments/office-chief-financial-officer/ocfo-divisions/office-contracting-and-procurement",
    "/departments/office-chief-financial-officer/ocfo-divisions/office-contracting-and-procurement/open-bids-city-detroit",
    "/departments/office-chief-financial-officer/ocfo-divisions/office-contracting-and-procurement/supplier-portal-information-and-instructions",
    "/departments/office-chief-financial-officer/ocfo-divisions/office-treasury/delinquent-property-tax-information",
    "/departments/office-chief-financial-officer/ocfo-divisions/office-treasury/income-tax",
    "/departments/office-chief-financial-officer/ocfo-divisions/office-treasury/income-tax/business-income-tax",
    "/departments/office-chief-financial-officer/ocfo-divisions/office-treasury/pay-property-tax",
]

don_urls = [
    "/departments/department-neighborhoods",
    "/departments/department-neighborhoods/motorcity-makeover-information",
    "/departments/department-neighborhoods/serve-detroit",
]

dpw_urls = [
    "/departments/department-public-works",
    "/departments/department-public-works/contact-us",
    "/departments/department-public-works/dead-animal-removal",
    "/departments/department-public-works/refuse-collection",
    "/departments/department-public-works/refuse-collection/bulk-yard-waste/curbside-bulk-waste-pickup",
    "/departments/department-public-works/refuse-collection/recycle",
    "/departments/department-public-works/street-maintenance",
]

health_urls = [
    "/departments/health-department",
    "/departments/health-department/birth-and-death-certificates",
    "/departments/health-department/detroit-animal-care-and-control",
    "/departments/health-department/detroit-id",
    "/departments/health-department/detroit-id/schedule-appointment",
    "/departments/health-department/food-safety",
    "/departments/health-department/immunizations",
    "/departments/health-department/sexually-transmitted-diseases-clinic",
]

hrd_urls = [
    "/departments/human-resources-department/apply-job",
    "/departments/human-resources-department/city-employee-information",
    "/departments/human-resources-department/employee-forms",
]

board_urls = [
    "/government/boards/board-electrical-examiners",
    "/government/boards/board-police-commissioners",
]

faq_urls = [
    "/node/1231",
    "/node/1521",
    "/node/1581",
    "/node/2471",
    "/node/2481",
    "/node/2501",
    "/node/2586",
    "/node/3361",
    "/node/3866",
    "/node/3886",
    "/node/4576",
    "/node/501",
    "/node/6476",
    "/node/9466",
    "/node/9871",
]

all_urls = city_council_urls + ddot_urls + dfd_urls + dpd_urls + \
    bseed_urls + pdd_urls + dah_urls + city_clerk_urls + mayors_office_urls + \
    dwsd_urls + media_services_urls + ocfo_urls + don_urls + dpw_urls + \
    health_urls + hrd_urls + board_urls + faq_urls

all_urls = sorted(set(all_urls))